store:
  availabilities:
    - German
    - International
  default_locale: en_GB
  localizations:
    - de_DE
    - en_GB
  categories:
    - ConversionOptimierung
  type: extension
  icon: src/Resources/store/icon.png
  automatic_bugfix_version_compatibility: false
  description:
    de: file:src/Resources/store/de.md
    en: file:src/Resources/store/en.md
  tags:
    de:
      - thumbnail
      - performance
      - storage
      - webp
    en:
      - thumbnail
      - performance
      - storage
      - webp
  features:
    de:
      - Keine Thumbnail-Dateien mehr
      - URL pro SalesChannel möglich
    en:
      - No more thumbnail files
      - URL per SalesChannel possible
  images:
    - file: src/Resources/store/0.png
      activate:
        de: true
        en: true
      preview:
        de: true
        en: true
      priority: 0
    - file: src/Resources/store/1.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 1
build:
  zip:
    assets:
      enable_es_build_for_admin: true
      enable_es_build_for_storefront: true


