name: Test
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [ "v6.5.0", "v6.5.1", "v6.5.2", "v6.5.3", "v6.5.4", "trunk" ]
    container: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          start-mysql
          mysql -V
          php -v
          cp -r "./" "/plugins/FroshPlatformThumbnailProcessor"
          cd /plugins/FroshPlatformThumbnailProcessor
          composer update -d /opt/shopware

      - name: Install specific dependencies for PHPUNIT
        if: matrix.version == 'v6.5.0'
        run: |
          composer require react/promise:~2 -d /opt/shopware/vendor-bin/roave-backward-compatibility-check

      - name: PHPUnit
        run: |
          php -d pcov.enabled=1 /opt/shopware/vendor/bin/phpunit  --coverage-clover clover.xml

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./clover.xml
          root_dir: /plugins/FroshPlatformThumbnailProcessor
          working-directory: /plugins/FroshPlatformThumbnailProcessor

      - name: Install specific dependencies for PHPStan
        if: matrix.version == 'v6.5.0'
        run: |
          composer require tomasvotruba/type-coverage --dev --no-scripts -d /opt/shopware/

      - name: PHPStan
        run: |
          cd /plugins/FroshPlatformThumbnailProcessor
          /opt/shopware/vendor/bin/phpstan analyse -c phpstan.neon
