name: Test
on:
  push:
    branches:
      - 'v4'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [ "v6.5.0", "v6.5.1", "v6.5.2", "v6.5.3", "v6.5.4", "v6.5.5", "v6.5.6", "v6.5.7", "6.5.x" ]
    container: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          start-mysql
          php /opt/shopware/bin/console -V
          mysql -V
          php -v
          cp -r "./" "/plugins/FroshPlatformThumbnailProcessor"
          cd /plugins/FroshPlatformThumbnailProcessor

      - name: PHPUnit
        run: |
          cd /plugins/FroshPlatformThumbnailProcessor
          php -d pcov.enabled=1 /opt/shopware/vendor/bin/phpunit  --coverage-clover clover.xml

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./clover.xml
          root_dir: /plugins/FroshPlatformThumbnailProcessor
          working-directory: /plugins/FroshPlatformThumbnailProcessor

      - name: Install specific dependencies for PHPStan at v6.5.0
        if: matrix.version == 'v6.5.0'
        run: |
          composer require tomasvotruba/type-coverage --dev --no-scripts -d /opt/shopware/

      # we call this after PHPUnit to make sure that the generated files are available
      - name: PHPStan
        run: |
          cd /plugins/FroshPlatformThumbnailProcessor
          /opt/shopware/vendor/bin/phpstan analyse -c phpstan.neon
