name: Test
on:
  push:
    branches:
      - 'v4'
    tags-ignore:
      - '*'
  pull_request:
  workflow_call:

jobs:
  test:
    env:
      PLUGIN_NAME: FroshPlatformThumbnailProcessor
    strategy:
      fail-fast: false
      matrix:
        version: [ "v6.5.1.1", "v6.5.2.1", "v6.5.3.3", "v6.5.4.1", "v6.5.5.2", "v6.5.6.1", "v6.5.7.4", "v6.5.8.7", "6.5.x" ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: ${{ matrix.version }}
          php-version: 8.2
          php-extensions: pcov

      - name: Info
        run: |
          php bin/console -V
          mysql -V
          php -v
          composer -V
          echo ${{ github.workspace }}

      - name: Checkout v4
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: v4
          path: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}

      - name: Checkout Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}

      - name: PHPUnit
        working-directory: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}
        run: |
          composer create-placeholders
          php -d pcov.enabled=1 ${{ github.workspace }}/vendor/bin/phpunit  --coverage-clover clover.xml

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./clover.xml
          root_dir: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}
          working-directory: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}

      # we call this after PHPUnit to make sure that the generated files are available
      - name: PHPStan
        run: |
          ${{ github.workspace }}/vendor/bin/phpstan analyse -c ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}/phpstan.neon
